tls:
#  certificates:
#    - certFile: /etc/traefik/certs/pmcdev-local.crt
#      keyFile: /etc/traefik/certs/pmcdev-local.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/pmcdev-local.crt
        keyFile: /etc/traefik/certs/pmcdev-local.key
