version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    labels:
      - "traefik.frontend.rule=HostRegexp:{domain:^traefik.*}"

    networks:
      traefik:
        ipv4_address: ${PMC_TRAEFIK_IP}
    ports:
      - "${PMC_DEV_BIND_IP}:80:80"
      - "${PMC_DEV_BIND_IP}:443:443"
      - "${PMC_DEV_BIND_IP}:8080:8080"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - './_wildcard.pmcdev.local.pem:/certs/_wildcard.pmcdev.local.pem'
      - './_wildcard.pmcdev.local-key.pem:/certs/_wildcard.pmcdev.local-key.pem'
networks:
  default:
    external:
       name: traefik
  traefik:
    external: true
