version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    command: '-c /dev/null --web --docker --logLevel=DEBUG --defaultEntryPoints=''http'',''https'' --entryPoints="Name:https Address::443 TLS:/certs/_wildcard.pmcdev.local.pem,/certs/_wildcard.pmcdev.local-key.pem" --entryPoints="Name:http Address::80"'
    labels:
      - "traefik.frontend.rule=HostRegexp:{domain:^traefik.*}"

    networks:
      traefik:
        ipv4_address: ${PMC_TRAEFIK_IP}
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './_wildcard.pmcdev.local.pem:/certs/_wildcard.pmcdev.local.pem'
      - './_wildcard.pmcdev.local-key.pem:/certs/_wildcard.pmcdev.local-key.pem'
networks:
  default:
    external:
       name: traefik
  traefik:
    external: true
