version: '3'

services:

  traefik:
    restart: always
    image: traefik:1.7
    container_name: traefik
    labels:
      - "traefik.frontend.rule=HostRegexp:{domain:^traefik.*}"
      - "traefik.port=8080" # enable this port so traefik can proxy it
    privileged: true
    networks:
      pmc-docker-qs:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/log/docker-container/traefik:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./config/ssl/local.pmcdev.io.crt:/etc/ssl/local.pmcdev.io.crt
      - ./config/ssl/local.pmcdev.io.key:/etc/ssl/local.pmcdev.io.key

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    labels:
      - "traefik.enable=false"
    networks:
      pmc-docker-qs:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume:

networks:
  default:
    external:
       name: pmc-docker-qs
  pmc-docker-qs:
    external: true
