version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    labels:
      - "traefik.frontend.rule=HostRegexp:{domain:^traefik.*}"
    networks:
      traefik:
        ipv4_address: ${PMC_TRAEFIK_IP}
    ports:
      - "${PMC_DEV_BIND_IP}:443:443"
      - "${PMC_DEV_BIND_IP}:8080:8080"
      - "${PMC_DEV_BIND_IP}:80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './_wildcard.pmcdev.local-key.pem:/certs/_wildcard.pmcdev.local-key.pem'
      - './_wildcard.pmcdev.local.pem:/certs/_wildcard.pmcdev.local.pem'
      - './traefik.toml:/etc/traefik/traefik.toml'
  watchtower:
    image: v2tec/watchtower
    restart: always
    command: watchtower pipeline-build pipeline-test wpdev --interval 30
    volumes:
      - "${HOME}/.docker/config.json:/config.json"
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
       name: traefik
  traefik:
    external: true
