version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    labels:
      - "traefik.frontend.rule=HostRegexp:{domain:^traefik.*}"

    networks:
      traefik:
        ipv4_address: ${PMC_TRAEFIK_IP}
    ports:
      - '443:443'
      - '8080:8080'
      - '80:80'
    volumes:
      - './_wildcard.pmcdev.local-key.pem:/certs/_wildcard.pmcdev.local-key.pem'
      - './_wildcard.pmcdev.local.pem:/certs/_wildcard.pmcdev.local.pem'
      - './traefik.toml:/etc/traefik/traefik.toml'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  default:
    external:
       name: traefik
  traefik:
    external: true
