# Accepted values, in order of severity: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# Messages at and above the selected level will be logged.
logLevel="ERROR"

defaultEntryPoints = ["http", "https"]

[api]
entryPoint = "traefik"
dashboard = true
debug = true

[traefikLog]

# Uncomment this to enable access logging
# [accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/wildcard.pmcdev.local.cert.pem"
      keyFile = "/certs/wildcard.pmcdev.local.key.pem"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "*.pmcdev.local"
watch = true
exposedByDefault = true
usebindportip = true
swarmMode = false
swarmModeRefreshSeconds = 15
